"""Build a compact Dream3R demo artifact directory."""

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from dream3r.visualize_ablation import create_visuals


ROOT = Path(__file__).resolve().parent


def _run_module(module: str, args: list[str]) -> str:
    cmd = [sys.executable, "-m", module, *args]
    proc = subprocess.run(
        cmd,
        cwd=ROOT.parent,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=True,
    )
    return proc.stdout


def _extract_json(text: str) -> dict:
    start = text.find("{")
    end = text.rfind("}")
    if start < 0 or end < start:
        raise ValueError("command output did not contain a JSON object")
    return json.loads(text[start:end + 1])


def export_showcase(out_dir: Path, windows: int, seeds: list[int]) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)

    demo_stdout = _run_module("dream3r.demo_mamba_path", [])
    demo_json = _extract_json(demo_stdout)
    demo_json_path = out_dir / "demo_mamba_path.json"
    demo_json_path.write_text(json.dumps(demo_json, indent=2) + "\n", encoding="utf-8")
    (out_dir / "demo_mamba_path.stdout.txt").write_text(demo_stdout, encoding="utf-8")

    ablation_json_path = out_dir / "ablation.json"
    ablation_stdout = _run_module(
        "dream3r.ablate_recurrence",
        ["--windows", str(windows), "--seeds", *[str(seed) for seed in seeds],
         "--output", str(ablation_json_path)],
    )
    (out_dir / "ablation.stdout.txt").write_text(ablation_stdout, encoding="utf-8")
    create_visuals(ablation_json_path, out_dir / "charts")

    docs = [
        "DEMO_SUMMARY.md",
        "INITIAL_RESEARCH_DEMO_PLAN.md",
        "RESEARCH_BASE_AND_INNOVATIONS.md",
        "SOTA_FEATURE_MATRIX.md",
        "NEXT_PHASE_ROADMAP.md",
        "ABLATION_BASELINE.md",
    ]
    copied_docs = []
    for doc in docs:
        src = ROOT / doc
        if src.exists():
            dst = out_dir / doc
            shutil.copyfile(src, dst)
            copied_docs.append(doc)

    manifest = {
        "created_at": datetime.utcnow().isoformat(timespec="seconds") + "Z",
        "windows": windows,
        "seeds": seeds,
        "files": {
            "demo_json": str(demo_json_path),
            "ablation_json": str(ablation_json_path),
            "charts_dir": str(out_dir / "charts"),
            "copied_docs": copied_docs,
        },
        "demo_summary": {
            "device": demo_json.get("device"),
            "variants": {
                item["recurrence_type"]: {
                    "backend": item.get("backend"),
                    "elapsed_ms_3_windows": item.get("elapsed_ms_3_windows"),
                    "state_delta_mean_abs": item.get("state_delta_mean_abs"),
                    "stable_promotion_rate": item.get("stable_promotion_rate"),
                }
                for item in demo_json.get("variants", [])
            },
        },
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

    readme = [
        "# Dream3R Showcase Artifacts",
        "",
        "This directory is generated by `python -m dream3r.export_demo_artifacts`.",
        "",
        "## Start Here",
        "",
        "- `manifest.json`: generated file list and demo summary.",
        "- `demo_mamba_path.json`: live demo output.",
        "- `ablation.json`: synthetic ablation output.",
        "- `charts/summary.md`: compact ablation table.",
        "- `charts/*.svg`: visual charts for slides.",
        "- `DEMO_SUMMARY.md`: presentation script.",
        "- `SOTA_FEATURE_MATRIX.md`: method-to-Dream3R mapping.",
        "- `NEXT_PHASE_ROADMAP.md`: next phase plan.",
        "",
        "## Caveat",
        "",
        "The ablation is synthetic integration evidence. It is not a real-data reconstruction quality claim.",
    ]
    (out_dir / "README.md").write_text("\n".join(readme) + "\n", encoding="utf-8")
    return manifest


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", default="demo_artifacts/showcase")
    parser.add_argument("--windows", type=int, default=3)
    parser.add_argument("--seeds", type=int, nargs="+", default=[33, 34, 35])
    args = parser.parse_args()

    manifest = export_showcase(Path(args.out_dir), args.windows, args.seeds)
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
